In [ ]:
import numpy as np
#initialize an empty array with size 2X2
emptyArray = np.empty((2,2))
emptyArray

array([[0., 0.],
       [0., 0.]])

In [ ]:
#Initialize an all one array with size 4X2.
onesArray = np.ones((4,2), dtype = int)
onesArray

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
#Return a new array of given shape and type, filled with fill value.{Hint: np.full}
fullArray = np.full((2,3),3)
fullArray

array([[3, 3, 3],
       [3, 3, 3]])

In [ ]:
#Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros_like}
arr = np.array([[1, 2, 3], [4, 5, 6]])

zeros_arr = np.zeros_like(arr)

print("Original array:")
print(arr)
print("\nZeros array:")
print(zeros_arr)

Original array:
[[1 2 3]
 [4 5 6]]

Zeros array:
[[0 0 0]
 [0 0 0]]


In [ ]:
#Return a new array of ones with same shape and type as a given array.{Hint: np.ones_like}
arr = np.array([[1, 2, 3], [4, 5, 6]])

onesArray = np.ones_like(arr)
print("Original array:")
print(arr)
print("\nOnes array:")
print(onesArray)

Original array:
[[1 2 3]
 [4 5 6]]

Ones array:
[[1 1 1]
 [1 1 1]]


In [ ]:
#For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

new_list =[1,2,3,4]

numpyArray = np.array(new_list)
print(numpyArray)
print(type(numpyArray))


[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#Array Manipulation
# Create an array with values ranging from 10 to 49. {Hint:np.arrange()}

random = np.arange(10,50)
random

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}
random = np.arange(0,9)

reshape = random.reshape(3,3)

reshape


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Create a 3X3 identity matrix.{Hint:np.eye()}

i_matrix = np.eye(3 , dtype = int)
i_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}
rand_arr = np.random.random(30)
print(rand_arr)
mean = rand_arr.mean()
print(mean)

[0.21051778 0.84041937 0.49952965 0.94582882 0.57468744 0.16355685
 0.99189382 0.17087789 0.02957703 0.70653475 0.45228369 0.57613002
 0.00785918 0.8780581  0.64913551 0.70663235 0.27729862 0.86455333
 0.99678648 0.96035692 0.56427965 0.0683012  0.33976892 0.56340714
 0.93076223 0.04188905 0.08129992 0.98305122 0.53945787 0.84493307]
0.5486555956803202


In [ ]:
# Create a 10X10 array with random values and find the minimum and maximum values.

random_arr = np.random.random((10,10))
min = random_arr.min()
max = random_arr.max()
print(min)
print(max)

0.0029477415197416423
0.9976420583013613


In [ ]:
# Create a zero array of size 10 and replace 5th element with 1.
a = np.zeros(10, dtype=int)
a[4] = 1

print(a)

[0 0 0 0 1 0 0 0 0 0]


In [ ]:
# Reverse an array arr = [1,2,0,0,4,0].

arr = [1,2,0,0,4,0]
reversed_arr = arr[::-1]

print(reversed_arr)


[0, 4, 0, 0, 2, 1]


In [ ]:
# Create a 2d array with 1 on border and 0 inside.
arr = np.ones((5, 5), dtype=int)
arr[1:-1, 1:-1] = 0

print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
# Create an 8x8 matrix of zeros
checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [51]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12]);

#Add two array.
add = x + y
print("Addition of two arrays")
print("------------------------------------------------------------------")
print(add)
print("\n")

#Subtract the two array
sub = w - v
print("Subtraction of two arrays")
print("------------------------------------------------------------------")
print(sub)
print("\n")

#Multuiply the array with any integer of your choice

multi_x = x *3
multi_y = y *2
multi_v = x *5
multi_w = x *7
print("this is for multiplication with any interger with my choice: ")
print("------------------------------------------------------------------")
print(f"multiplication of x: \n {multi_x}")
print(f"multiplication of y: \n{multi_y}")
print(f"multiplication of v: \n{multi_v}")
print(f"multiplication of w: \n{multi_w}")
print("\n")

#Find the square of each element of the array

square_x = x**2
square_y = y**2
square_v = v**2
square_w = w**2

print("this the square of each elements")
print("------------------------------------------------------------------")
print(f"Square of x: \n {square_x}")
print(f"Square of y: \n{square_y}")
print(f"Square of v: \n{square_v}")
print(f"Square of w: \n{square_w}")
print("\n")


#Find the dot product between: v(and)w ; x(and)v ; x(and)y.

dot_vw = np.dot(v,w)
dot_xv = np.dot(x,v)
dot_xy = np.dot(x,y)

print("Dot products")
print("------------------------------------------------------------------")
print(f"Square of x: \n {dot_vw}")
print(f"Square of y: \n{dot_xv}")
print(f"Square of v: \n{dot_xy}")
print("\n")

#Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.

xy_row = np.concatenate((x, y), axis=0)
vw_col = np.concatenate((v[:, None], w[:, None]), axis=1)

print("Concatination ")
print("------------------------------------------------------------------")
print(xy_row)
print(vw_col)
print("\n")

#Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

np.concatenate((x, v), axis=0)

#NumPy requires arrays to have the same number of dimensions when concatenating along a given axis.


Addition of two arrays
------------------------------------------------------------------
[[ 6  8]
 [10 13]]


Subtraction of two arrays
------------------------------------------------------------------
[2 2]


this is for multiplication with any interger with my choice: 
------------------------------------------------------------------
multiplication of x: 
 [[ 3  6]
 [ 9 15]]
multiplication of y: 
[[10 12]
 [14 16]]
multiplication of v: 
[[ 5 10]
 [15 25]]
multiplication of w: 
[[ 7 14]
 [21 35]]


this the square of each elements
------------------------------------------------------------------
Square of x: 
 [[ 1  4]
 [ 9 25]]
Square of y: 
[[25 36]
 [49 64]]
Square of v: 
[ 81 100]
Square of w: 
[121 144]


Dot products
------------------------------------------------------------------
Square of x: 
 219
Square of y: 
[29 77]
Square of v: 
[[19 22]
 [50 58]]


Concatination 
------------------------------------------------------------------
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [62]:
A = np.array([[3,4],[7,8]], dtype = int)
B = np.array([[5,3],[2,1]], dtype = int)


# 1. Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
result_int = np.round(result).astype(int)

print(f"A * A^-1 = \n {result_int}")
print("\n")


# 2. Prove AB ̸= BA.
result_ab= np.dot(A, B)
result_ba= np.dot(B, A)

print(f"AB = \n {result_ab}")
print(f"BA = \n {result_ba}")
print("Since the value of AB and BA are different, therefore AB ̸= BA.")
print("\n")

# 3. Prove (AB)T = BTAT

AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)
print("Since (AB)^T and B^TA^T are same therefore (AB)^T = B^TA^T ")
print("\n")

# 4.Solve the following system of Linear equation using Inverse Methods.
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])

x = np.linalg.solve(A_eq, B_eq).astype(int)

print("This is using only np.linalg only ")
print(x)
print("\n")

#Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}


a_inv = np.linalg.inv(A_eq)
x = np.dot(a_inv, B_eq).astype(int)
print("This is using np.linagl.inv function ")
print(x)




A * A^-1 = 
 [[1 0]
 [0 1]]


AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Since the value of AB and BA are different, therefore AB ̸= BA.


(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Since (AB)^T and B^TA^T are same therefore (AB)^T = B^TA^T 


This is using only np.linalg only 
[ 2  1 -2]


This is using np.linagl.inv function 
[ 2  1 -2]
